[book]
authors = ["448-OG <superuser@448.africa>"]
language = "en"
multilingual = false
src = "src"
title = "Deeper Understanding of Blockchains and Payments Infrastructure"

[output.html]
default-theme = "ayu"
git-repository-url = ""
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]

[output.html.fold]
enable = false
level = 1

[output.html.playground]
editable = true

[output.html.print]
enable = false
